"""empty message

Revision ID: 34054221f5cc
Revises: a75b0875284b
Create Date: 2021-02-16 10:50:09.879485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34054221f5cc'
down_revision = 'a75b0875284b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###
